### ISSUE TITLE
Netlify Deploy Preview

### ISSUE THREAD

**Issue by ekoeryanto** [renestalder/nuxt-netlify-cms-starter-template#11]
Hello, as it is an `netlify-cms-starter` template, it is good to use netlify deploy preview feature or/and netlify CI.
The problem is that we maybe need to use a special branch for it or to hardcode the instalation.

**Comment by renestalder** [comment]
You mean a live demo? That's planned and I recently have setup travis and all automation tasks to make this possible.

**Comment by ekoeryanto** [comment]
not just live demo but deploy preview 
https://www.netlify.com/docs/continuous-deployment/

**Comment by renestalder** [comment]
This is done in #18 and now live. So whenever you make a pull request, you have a preview of a generated test project.

At the same time, I added a better netlify-example config to the template that helps with setting up correct preview, branch and production generation with Netlify. I hope that helps.
