### ISSUE TITLE
Markdown instead of JSON

### ISSUE THREAD

**Issue by ekoeryanto** [renestalder/nuxt-netlify-cms-starter-template#2]

**Comment by renestalder** [comment]
Thanks for bringing this up.

Shouldn't be much of a problem. You can change the file glob in the `nuxt.config.js`, which currently looks for json files, but you could replace it with markdown:

```js
var dynamicRoutes = getDynamicPaths({
  '/blog': 'blog/posts/*.md'
});
```

And for the loading inside the vue component, you would need a JavaScript library to process markdown (which I never did at this point).

I'll keep that in mind to test it at some point and provide an example inside the template. Or if you already figure out a solution for your case, let me know.

**Comment by renestalder** [comment]
**Specification**:

* [Allowed formats by Netlify CMS](https://www.netlifycms.org/docs/configuration-options/#extension-and-format)

**Front matter format**:

* Convert from YAML Front Matter Format to JSON: [YAML Front matter Webpack loader](https://github.com/webpack-contrib/yaml-frontmatter-loader)

**Process markdown text**:
Then, this is optional but might be useful to provide in the tempate out-of-the-box:
* Convert markdown `body` to HTML. Options:
  * https://github.com/markedjs/marked
  * https://github.com/showdownjs/showdown

**Comment by ekoeryanto** [comment]
Hi, thanks for the guide.
is there a plan to use nuxtent module?

**Comment by renestalder** [comment]
Never heard of that. Looks interesting. I'll definitively check it. Thanks for the input.

**Comment by renestalder** [comment]
Checked out the nuxtent module. Very amazing.

Unfortunately it doesn't support Nuxt.js v1.0.0 yet. The rc.11 of Nuxt.js is the latest version that works together with Nuxtent.

I'll wait with this until Nuxtent patched the issues. Because they are now quite far behind the latest Nuxt version.

**Comment by ekoeryanto** [comment]
I think you haven't to use nuxtent, You have a better way to implement netlify-cms.

**Comment by ekoeryanto** [comment]
halo, come here just to write the reference.
https://github.com/craigdmckenna/markdown-it-front-matter
https://github.com/nuxt-community/modules/tree/master/packages/markdownit

**Comment by zanedev** [comment]
Hi I just tried your template, thanks it worked out of the box where others didn't..  I too would like to use md but I am new to nuxt.  If you don't mind, @ekoeryanto or @renestalder what are the exact steps to convert the template to use markdown?

**Comment by ekoeryanto** [comment]
Actually, as we write files by CMS (GUI), we don't need to care about the extension.
But the problem is, netlify cms use markdown widget and it writes markdown syntax.
For that problem we can use [markdownit module](https://github.com/nuxt-community/modules/tree/master/packages/markdownit) to compile the markdown [body](https://github.com/renestalder/nuxt-netlify-cms-starter-template/blob/master/template/content/blog/posts/2018-02-13-hello-world.json#L4)
But if the extension is important, you need to wait for @renestalder to implement the feature or you can try your self, replacing all `.json` string in the project and change netlify config to use markdown.

**Comment by renestalder** [comment]
Will try to take a close look to this in the coming weeks. Feel free to contribute your solutions if you already created one,

**Comment by renestalder** [comment]
Started working on this in #10

**Comment by suits-at** [comment]
Are there any updates yet?

**Comment by ekoeryanto** [comment]
Anyway, I decide to not use markdown, and use json because the `markdown-frontmatter` will be json at the end

**Comment by suits-at** [comment]
@ekoeryanto so instead of using markdown and compiling it with [markdownit ](https://github.com/nuxt-community/modules/tree/master/packages/markdownit) you use [marked ](https://www.npmjs.com/package/marked) to compile the given markdown from the CMS which is written into your .json files to proper html code? Did I get this right?

**Comment by suits-at** [comment]
Thx for clarification. Got it running meanwhile with `vue-markdown`.

**Comment by renestalder** [comment]
Just saw that nuxtent now works with Nuxt v1.0.0, which should make it much easier for me to add the full frontmatter/markdown support.

Currently adding nuxtent. Keep you updated.

**Comment by renestalder** [comment]
Little update here. Got it running in one of my projects and I'll transfer it to template here. But json will completely be gone. DO you often mixup markdown and json or do you rather only use one of both?

**Comment by renestalder** [comment]
For clarification, in my understanding, this is not about markdown rendering, but about markdown file type (frontmatter), which is the default in Netlify CMS.

As others pointed out, rendering markdown that is saved in json files is quite easy with vue-markdown.

**Comment by samSwitch** [comment]
Watching on with interest here.

Looks like Nuxtent is no longer maintained by the original author so will likely fall further behind as Nuxt approaches v2.

**Comment by renestalder** [comment]
> Looks like Nuxtent is no longer maintained by the original author so will likely fall further behind as Nuxt approaches v2.

That's what I fear too but in case the development will not adopt Nuxt 2, I'll just start to work on my own solution again or see if I can work with the code of Nuxtent. All in all the most difficult part is webpack splitting the contents correctly so they don't bloat the client side packages. Nuxtent solved that quite good as far as I can tell.

Also, currently I don't use Nuxtent because of the amount of bugs. I decided to use the nuxtdown fork, which works better for the moment.

**Comment by dev7ch** [comment]
@renestalder while searching nuxt / netlify repos i come here, i might have a solution for mapping all markdown files, extract frontmatter and auto generate dynamic routes from it.

You con see the code here: 
https://github.com/dev7ch/eloisa-florido-navarro.com/blob/master/nuxt.config.js

It's WIP and very experimental (cleanup not done yet)

Hope this could help to enhance your Kickstarter Project

**Comment by danchristian** [comment]
Any updates on this?

**Comment by renestalder** [comment]
Sorry for not following up. I have this ready for quite some time by now, but didn't copy back my changes to this repository. I'll fix the time for following Friday to do that. Thanks for signal.

**Comment by renestalder** [comment]
See #10 for first working version. I only checked for pages yet (Netlify CMS' files collection). Will have to add an example of dynamic collections e.g. blog posts too.

**Comment by renestalder** [comment]
I just recently found out about Gridsome, which is mainly the Vue.js equivalent of React's Gatsby.js.
https://gridsome.org/

I wonder, with this, is it still interesting that I provide a working example of the template here? AS it's not even up to date with the latest Nuxt version. And I would most likely try out Gridsome at some point and probably switch.

The main goal of this template here came out of the situation, that I didn't found any starter kit for Netlify CMS combined with static generation.

**Comment by suits-at** [comment]
There are already community projects to integrate gridsome with netlifycms for example [this one](https://github.com/mittalyashu/gridsome-starter-netlifycms) and  "Gridsome is working on an official starter for NetlifyCMS" too ([see here](https://github.com/netlify/netlify-cms/pull/1895)). Therefore, from my point of perspective, there is no need on any further updates on this repo.

**Comment by renestalder** [comment]
I guess the question is if people want to use Nuxt as foundation, even Gridsome might do the exact same.

But I do not plan to update the repository for Vue CLI v3 and Nuxt v2 currently with the discovery of Gridsome. The fact that Gridsome handles different content types out of the box, where I "fight" to do the same (and changed everything to frontmatter/markdown without json support anymore) is just fantastic.

**Comment by renestalder** [comment]
I merged the changes to master. I recently made some tests with Gridsome and think this thing will take quite a while to be stable.

As I use this template here in production and I'm very happy how it is performing so far, so as long as Gridsome doesn't get stable, I'll add additions and improve the template.
