### ISSUE TITLE
Nuxtdown doesn't render the pages? 404 request failure

### ISSUE THREAD

**Issue by catman85** [renestalder/nuxt-netlify-cms-starter-template#27]
**Describe the bug**
When I attempt to visit a page that is consisted of markdown content (Page1 or Page2),
I get the following message from Nuxt.js:
[![image.png](https://i.postimg.cc/4Nmv4WKv/image.png)](https://postimg.cc/WhcqX6wt)

**To Reproduce**
- I made a repo that is a result of a fresh "vue init ..." from your template
- Here it is: https://github.com/catman85/gallery-nuxt-cms
- and here is the live site: https://epic-bhaskara-02f420.netlify.com/
- I have succesfuly setup NetlifyCMS and I am able to add blogs and pages, (after running git pull locally, I can see the new files).

**Additional context**
I made an about page to test if routing works properly, and it does.
I tried to read nuxtdown's docs and I can't figure out what's wrong.
Am I missing something?
Please Help!
Great Project btw keep it up!

**Comment by renestalder** [comment]
Oh well, the Nuxtdown/Nuxtent docs aren't always as clear as they could be, no worry. The 404 is quite a common error.

Do you face the same problem when you running the local dev server or does it only happen when deployed?

I see that the Netlify Config in your repository in unused, so I assume you don't use Netlify for hosting. In this case, [you need to manually set the final URL of your website before building](https://github.com/renestalder/nuxt-netlify-cms-starter-template#manual-deployment-via-ftp) so the static generated pages are working correctly.

**Comment by catman85** [comment]
I actually use Netlify for hosting, so after reading your docs a bit better, I pushed another commit, where I renamed "netlify-example.toml" to "netlify.toml" https://github.com/catman85/gallery-nuxt-cms/commit/51939a6dadffd8e5338bfb50b2872cb72326d225.
And it works on the live server.🎆

🤔 But it still doesn't work on my local dev server when I run "npm run serve".

**Comment by catman85** [comment]
Update: 
it works flawlessly locally on Linux Mint (node v8.15.1 ,npm 6.4.1), 
but not on Windows 7 (node v10.14.2, npm v6.4.1)

**Comment by renestalder** [comment]
@catman85 Okay, that something. But I fear I will not be able to fix this. There are so many npm dependencies which just simply do not work on Windows machine, the error can be hidden deep in the structure. And as this is simply a boilerplate leveraging other tools without adding any real features, that problem seems not related to my work and not simply be a fix on my repository.

So I sadly have to say I cannot help you to make this working on Windows at this moment.

**Comment by catman85** [comment]
That's ok, thank you for your help.
