### ISSUE TITLE
Can't Import Vue Components into Page

### ISSUE THREAD

**Issue by semanley** [renestalder/nuxt-netlify-cms-starter-template#28]
Everything's been working great so far with this project, but I've hit a wall with trying to import a Vue component into the index.vue of one of my pages. 

The component lives in the `/components` directory, and I'm referencing it at the top of the `<script>` like so: `import FeeRow from '~components/FeeRow.vue'`. But whether I use the `~` syntax, or a relative path, I always get the same error: 

```
This dependency was not found:

* ~components/FeeRow.vue in ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-
loader-options!./pages/professional-practice-plan/index.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save ~components/FeeRow.vue
```

It looks to me like the script expects the component to be installed in `/node_modules`, instead of in `/components`. I've looked everywhere for a solution, but I can't find anyone that's even had the same issue. 

This particular bit of code needs to live as a component, so any help would be appreciated! Thanks!

![Screen Shot 2019-04-23 at 9 38 54 AM](https://user-images.githubusercontent.com/31714878/56589996-e22e2a00-65ab-11e9-870b-ec19745f6bf1.png)

**Comment by renestalder** [comment]
That error doesn't have anything to do with this boilerplate but here we go: Check that you use `import FeeRow from '~/components/FeeRow.vue';` instead of `import FeeRow from '~components/FeeRow.vue`. From your error it looks like you are missing a slash after the Tilde Webpack alias.

-------- Original Message --------

**Comment by semanley** [comment]
I'm an idiot. You're a lifesaver. Thank you so much!
