### ISSUE TITLE
Vue init setup strips out slug definitions of Netlify CMS config

### ISSUE THREAD

**Issue by ekoeryanto** [renestalder/nuxt-netlify-cms-starter-template#3]
test create post with netlify, it create file with no name 
https://github.com/ekoeryanto/nuxtify-cms/tree/master/content/blog/posts

**Comment by renestalder** [comment]
I see. Probably a problem of the template setup via vue-cli init.

Check your Netlify CMS config. The slug is  `---` which is wrong and I assume was stripped out by the vue init setup process I use.

Will fix that. You should be able to update the slug (check the Netlify CMS documentation or the files in this repository) and then it should work.

**Comment by ekoeryanto** [comment]
Thanks for the fix.
I am sorry for the late, I have no idea how github not to sent me notification about comment.
