### ISSUE TITLE
Post not working

### ISSUE THREAD

**Issue by ekoeryanto** [renestalder/nuxt-netlify-cms-starter-template#4]
![image](https://user-images.githubusercontent.com/36023898/37142003-627571d4-22e9-11e8-8bad-53883e93b153.png)

**Comment by renestalder** [comment]
I currently doubt this is a fault of the template. But let's see. Can you post your Netlify CMS config?

**Comment by ekoeryanto** [comment]
I just forked and deployed it without change anything.

**Comment by renestalder** [comment]
Just [forked your branch](https://github.com/renestalder/nuxtify-cms) and made the changes as discussed in #3 and it works fine so far. Please check your Netlify CMS configurations otherwise.

**Comment by ekoeryanto** [comment]
Did you post by netlify admin?
Everything works fine if I just creating a json file manually.
ps: This issue came with latest commit cc45da3d746ad742fd933e6723856ae1b9f5184c, before it created a file without filename.

I'll try again by re fork the or merge the newly commit to confirm this issue.

**Comment by renestalder** [comment]
Yep, did the post via Netlify CMS admin. But would be interesting what you tried to post. Anyway, I still think it might not be a problem of my code and rather one in the Netlify configuration or the Netlify CMS.

Or possibly the problem was just solves by setting the slug property correctly because, of course, in your repository, it tried to create a post with the same file name.

**Comment by ekoeryanto** [comment]
Halo, it works, one thing I forgot is to enable git-gateway.

I think we have to add that to the readme

**Comment by renestalder** [comment]
Yeah, good point. I wanted to keep out Netlify CMS setup steps in the readme, since I stated one should read the official documentation for setting this up. But it seems like a bit of duplication is more useful here.

Thanks for the feedback.

**Comment by ekoeryanto** [comment]
Ya, that's no need to tell the user if they read the source, but sometime user just want to (quick) test for the functionality of the lib/software. 
> it seems like a bit of duplication is more useful here

Agreed, to prevent issue like this.
